levels:
  1:
    answers:
      '1': aWY=
      '2': YW5k
      '3': ZWxzZQ==
      '4': ZGVm
    challenge: VGhpcyBjaGFsbGVuZ2UgaXMgYWJvdXQgUHl0aG9uIGtleXdvcmRzLiBUaGUgX19fMV9fXyBrZXl3b3JkIGlzIGEgbG9naWNhbCBvcGVyYXRvciB1c2VkIHRvIGNvbXBhcmUgdHdvIHN0YXRlbWVudHMuIEZvciBleGFtcGxlLCBfX18xX19fIDEgPT0gMTogLiBUaGUgX19fMl9fXyBrZXl3b3JkIGlzIHVzZWQgdG8gdmFsaWRhdGUgaWYgQk9USCBzdGF0ZW1lbnRzIGFyZSB0cnVlLiBGb3IgZXhhbXBsZSwgMSA9PSAxIF9fXzJfX18gMiA9PSAyOiBUaGUgX19fM19fXyBrZXl3b3JkIHRlbGxzIHB5dGhvbiB3aGF0IHRvIGRvIGlmIG5vbmUgb2YgdGhlIGxvZ2ljYWwgY29tcGFyaXNvbnMgd2VyZSB0cnVlLiBGb3IgZXhhbXBsZSwgX19fMV9fXyAxID09IDEgX19fMl9fXyAyID09IDM6IGRvIHRoaXMgZmlyc3QuIF9fXzNfX186IGRvIHNvbWV0aGluZyBkaWZmZXJlbnQuIFRoZSBfX180X19fIGtleXdvcmQgaXMgdXNlZCB0byBkZWZpbmUgYSBmdW5jdGlvbi4=
  2:
    answers:
      '1': aW50ZWdlcg==
      '2': ZmxvYXQ=
      '3': Ym9vbGVhbg==
      '4': c3RyaW5n
    challenge: VGhpcyBjaGFsbGVuZ2UgaXMgYWJvdXQgcHl0aG9uIGRhdGEgdHlwZXMuIEFuIF9fXzFfX18gaXMgYSB3aG9sZSBudW1iZXIgdGhhdCBjYW4gYmUgbmVnYXRpdmUgb3IgcG9zaXRpdmUuIEEgX19fMl9fXyBpcyBhbHNvIGEgbnVtYmVyIHRoYXQgY2FuIGJlIG5lZ2F0aXZlIG9yIHBvc2l0aXZlLCBidXQgY29udGFpbnMgYSBkZWNpbWFsIHBvaW50LiBBIF9fXzNfX18gaXMgZWl0aGVyIFRydWUgb3IgRmFsc2UuIEEgX19fNF9fXyBzdG9yZXMgdGV4dC4=
  3:
    answers:
      '1': YXJpdGhtZXRpYw==
      '2': Y29tcGFyaXNvbg==
      '3': YXNzaWdubWVudA==
      '4': bWVtYmVyc2hpcA==
    challenge: VGhpcyBjaGFsbGVuZ2UgaXMgYWJvdXQgcHl0aG9uIG9wZXJhdG9yIHR5cGVzLiBfX18xX19fIG9wZXJhdG9ycyBkbyBtYXRoZW1hdGljYWwgZnVuY3Rpb25zIGxpa2UgMSArIDEsIG9yIDMuMTQgKiogMiwgb3IgNSAlIDIgPSAxLiBfX18yX19fIG9wZXJhdG9ycyBldmFsdWF0ZSB0aGluZ3MgbGlrZSBhID09IGIsIG9yIFRydWUgIT0gRmFsc2UsIG9yIDMgPD0gMi4gX19fM19fXyBvcGVyYXRvcnMgc2V0IHRoZSB2YWx1ZSBvZiBhIHZhcmlhYmxlLiBGb3IgZXhhbXBsZSB2YXJpYWJsZSA9ICd2YWx1ZScsIG9yIGluY3JlbWVudCArPSAxLCBvciBkZWNyZW1lbnQgLT0gMS4gUHl0aG9uIF9fXzRfX18gb3BlcmF0b3JzIGRldGVybWluZSBpZiBzb21ldGhpbmcgaXMgZm91bmQgaW4gYSBzZXF1ZW5jZS4gRm9yIGV4YW1wbGUsICJ4IGluIHkiICJ4IG5vdCBpbiByYW5nZSgxMCkiLiBJZiB5b3UgbmVlZCBoZWxwLCBnbyB0byBodHRwczovL3d3dy50dXRvcmlhbHNwb2ludC5jb20vcHl0aG9uL3B5dGhvbl9iYXNpY19vcGVyYXRvcnMuaHRt
settings:
  encoding: true
  version: 1
